name: igcuda
channels:
  - conda-forge
  - nvidia/label/cuda-12.4.0
dependencies:
  - python=3.10
  - cuda-toolkit
  - libglvnd
  - mesalib
  - libegl
  - libgles
  - libglvnd-devel-conda-x86_64
  - libegl-devel
  - libgles-devel