assets_path: assets # put either absolute path or relative to current directory
g_dataset_path: assets/g_dataset
ig_dataset_path: assets/ig_dataset
threedfront_dataset_path: assets/threedfront_dataset
cubicasa_dataset_path: assets/cubicasa_dataset
