# scene
scene: building
model_id: candcenter
build_graph: true
load_texture: true
should_load_replaced_objects: false
should_load_additional_objects: false
trav_map_erosion: 3

# robot
robot: Fetch
velocity: 0.1
fine_motion_plan: true

# task, observation and action
task: pointgoal # pointgoal|objectgoal|areagoal|reaching
fisheye: false

initial_pos: [-1.0, -1.0, 0.0]
initial_orn: [0.0, 0.0, 0.0]

target_pos: [1.0, 1.0, 0.0]
target_orn: [0.0, 0.0, 0.0]

is_discrete: false
additional_states_dim: 22

# reward
reward_type: dense
success_reward: 10.0
slack_reward: 0.0
potential_reward_weight: 1.0
electricity_reward_weight: 0.0
stall_torque_reward_weight: 0.0
collision_reward_weight: -0.0
collision_ignore_link_a_ids: [0, 1, 2, 3, 20, 21, 22]  # ignore collision with these agent's link ids

# discount factor
discount_factor: 0.99

# termination condition
death_z_thresh: 0.2
dist_tol: 0.5  # body width
max_step: 25

# sensor
output: [sensor, rgb, depth, scan]
resolution: 128
fov: 57.5
n_horizontal_rays: 220
n_vertical_beams: 1
scan_noise_rate: 0.02
depth_noise_rate: 0.02

# display
use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose: false
  random_target_pose: false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

speed:
  timestep: 0.001
  frameskip: 10

mode: web_ui #gui|headless
verbose: false
fast_lq_render: true

# visual objects
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: false

# debug
debug: false
