# scene
scene: igibson
scene_id: Rs_int
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: no_obj
trav_map_resolution: 0.1
trav_map_erosion: 2
should_open_all_doors: true

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
robot: Locobot
linear_velocity: 0.5
angular_velocity: 1.5707963267948966

# task, observation and action
task: object_nav
reward_type: relative
reward_scale: 200.0
success_reward: 10.0
success_thresh: 0.05
additional_states_dim: 4

# reward
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

# discount factor
discount_factor: 0.99

# termination condition
max_step: 500
max_collisions_allowed: 500

# sensor spec
output: [sensor, rgb, depth]
# image
# ASUS Xtion PRO LIVE
# https://www.asus.com/us/3D-Sensor/Xtion_PRO_LIVE
fisheye: false
image_width: 512
image_height: 512
vertical_fov: 120

# depth
depth_low: 0.1
depth_high: 10.0

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: false

