# scene
scene: building
model_id: Ohoopee
build_graph: true
load_texture: true
trav_map_erosion: 2

# robot
robot: Locobot
velocity: 0.1

# task, observation and action
task: pointgoal # pointgoal|objectgoal|areagoal|reaching
fisheye: false

is_discrete: false
additional_states_dim: 3

# reward
reward_type: geodesic
success_reward: 10.0
slack_reward: -0.01
potential_reward_weight: 1.0
collision_reward_weight: -0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collision with these agent's link ids

# discount factor
discount_factor: 0.99

# termination condition
death_z_thresh: 0.2
dist_tol: 0.333  # body width
max_step: 500

# sensor
output: [sensor, rgb, depth]
resolution: 256
fov: 90

# display
use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose: false
  random_target_pose: false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

speed:
  timestep: 0.001
  frameskip: 10

mode: web_ui #gui|headless
verbose: false
fast_lq_render: true

# debug
debug: false
